# REQUIRED CONFIG

OWNER_ID = 957158815
TELEGRAM_API = 25031723
TELEGRAM_HASH = "5118037e6d6a03a2fc4a75262d72cef9"
# OPTIONAL CONFIG
BOT_TOKEN = '7594684546:AAGghyZIFXDar-mh56hVYJ0ys2ors1oENMk'
UPSTREAM_REPO = "https://github.com/AeonOrg/Aeon-MLTB"
UPSTREAM_BRANCH = "main"
UPGRADE_PACKAGES = ""
DATABASE_URL = 'mongodb://d:d@joker_d:27017/?tls=false'
USER_SESSION_STRING = 'BAB3zgYASJpQvvRn6VBepOJL5ZKQQw-aDPkAdxfziOTcFh5FsiNE2jcDk9iQdePB4zkAXY_KmNWL1wq_EI1fntWmbxFu0PDQUg03jF-u8-5wjF-SoD4i0wL14b7tFTiWn5LKz9A-Hyva4kH2VSEm2ZbouDoJ7F-rKdR4ZppFvklhmMCgRQSoEmuTFMFSJvkbX38zJwtK1iLtI7sH1Ae2Hwf-k9V9DhTCe1KFBdRC1x4KFRnm5MFBZ_udWEK4s_0_Hm8S7bxWGMwCicq5kZGghuk-svWu57yw5Jqx3JSKufkbjzu7dc_UF8nYviJjl5X_Fo1btA07dqpbNF6Ikqpvk5OIzJWXtQAAAABwClvxAA'
LEECH_DUMP_ID= -1002408745986

# SEMI-REQUIRED, WE SUGGEST TO FILL IT FROM MONGODB

# OPTIONAL CONFIG

DOWNLOAD_DIR = "/usr/src/app/downloads/"
CMD_SUFFIX = ""
AUTHORIZED_CHATS = ""
SUDO_USERS = ""
DEFAULT_UPLOAD = "rc"
FILELION_API = ""
STREAMWISH_API = ""
EXTENSION_FILTER = ""
INCOMPLETE_TASK_NOTIFIER = False
YT_DLP_OPTIONS = ""
USE_SERVICE_ACCOUNTS = False
NAME_SUBSTITUTE = ""
FFMPEG_CMDS = {}

# INKYPINKY
DELETE_LINKS = False
FSUB_IDS = ""
TOKEN_TIMEOUT = 0
PAID_CHANNEL_ID = 0
PAID_CHANNEL_LINK = ""
SET_COMMANDS = True
METADATA_KEY = ""
WATERMARK_KEY = ""
LOG_CHAT_ID = 0
LEECH_FILENAME_CAPTION = ""

# GDrive Tools
GDRIVE_ID = ""
IS_TEAM_DRIVE = False
STOP_DUPLICATE = False
INDEX_URL = ""

# Rclone
RCLONE_PATH = ""
RCLONE_FLAGS = ""
RCLONE_SERVE_URL = ""
RCLONE_SERVE_PORT = 0
RCLONE_SERVE_USER = ""
RCLONE_SERVE_PASS = ""

# Mega credentials
MEGA_EMAIL = ""
MEGA_PASSWORD = ""

# Update
UPSTREAM_REPO = "https://github.com/AeonOrg/Aeon-MLTB"
UPSTREAM_BRANCH = "main"

# Leech
LEECH_SPLIT_SIZE = 0
AS_DOCUMENT = False
MEDIA_GROUP = False
USER_TRANSMISSION = False
MIXED_LEECH = False
LEECH_FILENAME_PREFIX = ""

THUMBNAIL_LAYOUT = ""

# qBittorrent/Aria2c
TORRENT_TIMEOUT = 0
BASE_URL = ""
BASE_URL_PORT = 80
WEB_PINCODE = False

# Queueing system
QUEUE_ALL = 0
QUEUE_DOWNLOAD = 0
QUEUE_UPLOAD = 0

# RSS
RSS_DELAY = 600
RSS_CHAT = ""
RSS_SIZE_LIMIT = 0
